import hashlib
import importlib.util
import json
import sqlite3
import tempfile
import unittest
from pathlib import Path


MODULE_PATH = Path(__file__).with_name("recovery_package.py")
SPEC = importlib.util.spec_from_file_location("recovery_package", MODULE_PATH)
recovery_package = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(recovery_package)


class RecoveryPackageTests(unittest.TestCase):
    def make_fixture(self):
        temporary = tempfile.TemporaryDirectory()
        root = Path(temporary.name)
        payload = root / "raw" / "source.txt"
        payload.parent.mkdir()
        payload.write_text("captured source\n", encoding="utf-8")

        database = root / "mt_uniforms_recovery.sqlite"
        connection = sqlite3.connect(database)
        connection.execute(
            """CREATE TABLE source_manifest(
                source_id INTEGER PRIMARY KEY,
                system TEXT NOT NULL,
                artifact_type TEXT NOT NULL,
                source_path TEXT,
                captured_at TEXT,
                sha256 TEXT,
                bytes INTEGER,
                status TEXT NOT NULL,
                notes TEXT
            )"""
        )
        connection.execute(
            """INSERT INTO source_manifest(
                system, artifact_type, source_path, captured_at, sha256, bytes, status, notes
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                "fixture",
                "source",
                "raw/source.txt",
                "2026-08-09T00:00:00Z",
                hashlib.sha256(payload.read_bytes()).hexdigest(),
                payload.stat().st_size,
                "captured",
                "test fixture",
            ),
        )
        connection.commit()
        connection.close()

        (root / "package-manifest.json").write_text(
            json.dumps(
                {
                    "package": "mt-uniforms-recovery",
                    "generated_at": "2026-08-09T00:00:00Z",
                    "root": "C:/stale/machine/path",
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return temporary, root

    def test_upgrade_makes_package_portable_and_verifiable(self):
        temporary, root = self.make_fixture()
        self.addCleanup(temporary.cleanup)

        recovery_package.upgrade_package(root)
        report = recovery_package.verify_package(root)

        self.assertTrue(report["valid"])
        self.assertEqual(report["schema_version"], "1.1.0")
        self.assertEqual(report["database_user_version"], 2)
        self.assertEqual(report["database_application_id"], recovery_package.APPLICATION_ID)
        self.assertEqual(
            report["record_counts"],
            {
                "business_entities": 0,
                "business_facts": 0,
                "infrastructure_assets": 0,
                "infrastructure_observations": 0,
                "asset_control_claims": 0,
            },
        )
        manifest = json.loads((root / "package-manifest.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["root"], ".")
        self.assertEqual(manifest["schema_version"], "1.1.0")
        self.assertEqual(
            manifest["work_scope_migration"]["status"],
            "legacy-source-snapshots-preserved",
        )
        self.assertTrue((root / "SHA256SUMS.txt").is_file())

    def test_verifier_detects_payload_tampering(self):
        temporary, root = self.make_fixture()
        self.addCleanup(temporary.cleanup)
        recovery_package.upgrade_package(root)
        (root / "raw" / "source.txt").write_text("tampered\n", encoding="utf-8")

        with self.assertRaisesRegex(ValueError, "checksum mismatch"):
            recovery_package.verify_package(root)

    def test_verifier_ignores_generated_python_bytecode(self):
        temporary, root = self.make_fixture()
        self.addCleanup(temporary.cleanup)
        recovery_package.upgrade_package(root)
        cache = root / "tools" / "__pycache__"
        cache.mkdir(parents=True)
        (cache / "verifier.cpython-test.pyc").write_bytes(b"generated bytecode")

        report = recovery_package.verify_package(root)

        self.assertTrue(report["valid"])

    def test_verifier_rejects_absolute_source_paths(self):
        temporary, root = self.make_fixture()
        self.addCleanup(temporary.cleanup)
        recovery_package.upgrade_package(root)
        database = root / "mt_uniforms_recovery.sqlite"
        connection = sqlite3.connect(database)
        connection.execute(
            "UPDATE source_manifest SET source_path = ? WHERE source_id = 1",
            ("C:/private/export.csv",),
        )
        connection.commit()
        connection.close()
        recovery_package.write_checksums(root)

        with self.assertRaisesRegex(ValueError, "source_manifest contains absolute paths"):
            recovery_package.verify_package(root)

    def test_upgrade_adds_record_level_provenance_schema(self):
        temporary, root = self.make_fixture()
        self.addCleanup(temporary.cleanup)

        recovery_package.upgrade_package(root)
        connection = sqlite3.connect(root / "mt_uniforms_recovery.sqlite")
        try:
            tables = {
                row[0]
                for row in connection.execute(
                    "SELECT name FROM sqlite_master WHERE type='table'"
                )
            }
            source_columns = {
                row[1] for row in connection.execute("PRAGMA table_info(source_manifest)")
            }
        finally:
            connection.close()

        self.assertTrue(
            {
                "business_entities",
                "business_facts",
                "infrastructure_assets",
                "infrastructure_observations",
                "asset_control_claims",
            }.issubset(tables)
        )
        self.assertTrue(
            {"source_ref", "source_uri", "capture_method", "record_count", "completeness"}.issubset(
                source_columns
            )
        )


if __name__ == "__main__":
    unittest.main()
